############################################################
# 03_core_temporal_gene_identification_and_intersection_plot.R
#
# Purpose:
#   Intersect time-point DEGs with maSigPro temporal genes
#   Draw publication-ready SCI-style Venn diagram
#
# Labels:
#   Time-point DEGs
#   maSigPro temporal genes
#
# Classic SCI Venn palette:
#   left circle  = #6BA3D6
#   right circle = #E58B8B
#   overlap      = generated by transparent blending
#
# 
############################################################

rm(list = ls())
options(stringsAsFactors = FALSE)

############################################################
# 0) Paths
############################################################
base_dir <- "D:/WeiRuan/NiV/GSE166707/results_FINAL_timepoint_FULL_SCI"

deg_file <- file.path(base_dir, "06_Mfuzz", "DEG_union.csv")

masigpro_file <- file.path(
  base_dir,
  "08_maSigPro",
  "旧版",
  "k6_results",
  "cluster_gene_mapping_k6.csv"
)

out_dir <- file.path(base_dir, "09_Intersection_DEG_maSigPro_k6_SCI_Venn_v5")
dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)

if (!file.exists(deg_file)) stop("Missing DEG file: ", deg_file)
if (!file.exists(masigpro_file)) stop("Missing maSigPro file: ", masigpro_file)

############################################################
# 1) Packages
############################################################
need_pkgs <- c("dplyr", "stringr", "ggplot2", "ggforce")

miss <- need_pkgs[!vapply(need_pkgs, requireNamespace, logical(1), quietly = TRUE)]
if (length(miss) > 0) install.packages(miss, dependencies = TRUE)

suppressPackageStartupMessages({
  library(dplyr)
  library(stringr)
  library(ggplot2)
  library(ggforce)
})

############################################################
# 2) Helper functions
############################################################
detect_gene_col <- function(df) {
  candidates <- c(
    "gene_symbol", "gene", "Gene", "GENE",
    "GeneSymbol", "SYMBOL", "symbol",
    "genes", "Genes", "基因名"
  )
  hit <- candidates[candidates %in% colnames(df)]
  if (length(hit) > 0) return(hit[1])
  colnames(df)[1]
}

clean_gene <- function(x) {
  x <- as.character(x)
  x <- str_trim(x)
  x <- x[!is.na(x) & x != ""]
  unique(toupper(x))
}

############################################################
# 3) Read data
############################################################
deg_df <- read.csv(deg_file, check.names = FALSE, stringsAsFactors = FALSE)
deg_col <- detect_gene_col(deg_df)
deg_genes <- clean_gene(deg_df[[deg_col]])

masigpro_df <- read.csv(masigpro_file, check.names = FALSE, stringsAsFactors = FALSE)

if (all(c("Cluster", "Gene") %in% colnames(masigpro_df))) {
  masigpro_gene_col <- "Gene"
} else if (all(c("聚类编号", "基因名") %in% colnames(masigpro_df))) {
  masigpro_gene_col <- "基因名"
} else {
  masigpro_gene_col <- colnames(masigpro_df)[2]
}

masigpro_genes <- clean_gene(masigpro_df[[masigpro_gene_col]])

############################################################
# 4) Counts
############################################################
intersect_genes <- intersect(deg_genes, masigpro_genes)

n_deg <- length(deg_genes)
n_msp <- length(masigpro_genes)
n_int <- length(intersect_genes)

n_deg_only <- n_deg - n_int
n_msp_only <- n_msp - n_int

############################################################
# 5) Save intersect genes
############################################################
write.csv(
  data.frame(Gene = intersect_genes),
  file.path(out_dir, "intersect_Timepoint_DEGs_maSigPro_temporal_genes.csv"),
  row.names = FALSE
)

############################################################
# 6) Colors: classic SCI Venn palette
############################################################
COL_DEG <- "#6BA3D6"
COL_MSP <- "#E58B8B"

############################################################
# 7) Plot data
############################################################
circle_left <- data.frame(
  x0 = -0.68,
  y0 = 0,
  r  = 1.18
)

circle_right <- data.frame(
  x0 = 0.68,
  y0 = 0,
  r  = 1.18
)

count_df <- data.frame(
  label = c(n_deg_only, n_int, n_msp_only),
  x = c(-1.08, 0, 1.08),
  y = c(0, 0, 0)
)

label_df <- data.frame(
  label = c("Time-point DEGs", "maSigPro temporal genes"),
  x = c(-1.08, 1.08),
  y = c(1.47, 1.47),
  col = c(COL_DEG, COL_MSP)
)

############################################################
# 8) Draw Venn
############################################################
p <- ggplot() +
  
  geom_circle(
    data = circle_left,
    aes(x0 = x0, y0 = y0, r = r),
    fill = COL_DEG,
    color = "black",
    alpha = 0.50,
    linewidth = 0.65
  ) +
  
  geom_circle(
    data = circle_right,
    aes(x0 = x0, y0 = y0, r = r),
    fill = COL_MSP,
    color = "black",
    alpha = 0.50,
    linewidth = 0.65
  ) +
  
  geom_text(
    data = count_df,
    aes(x = x, y = y, label = label),
    size = 6.4,
    fontface = "bold",
    color = "black"
  ) +
  
  geom_text(
    data = label_df,
    aes(x = x, y = y, label = label, color = col),
    size = 4.7,
    fontface = "bold"
  ) +
  
  scale_color_identity() +
  
  coord_fixed(
    xlim = c(-2.05, 2.05),
    ylim = c(-1.35, 1.70),
    clip = "off"
  ) +
  
  theme_void(base_size = 13) +
  
  theme(
    legend.position = "none",
    plot.background = element_rect(fill = "white", color = NA),
    panel.background = element_rect(fill = "white", color = NA),
    plot.margin = margin(8, 8, 8, 8)
  )

############################################################
# 9) Save figures
############################################################
ggsave(
  filename = file.path(out_dir, "SCI_Venn_Timepoint_DEGs_maSigPro_temporal_genes.pdf"),
  plot = p,
  width = 6.4,
  height = 4.6,
  bg = "white",
  device = cairo_pdf
)

ggsave(
  filename = file.path(out_dir, "SCI_Venn_Timepoint_DEGs_maSigPro_temporal_genes.png"),
  plot = p,
  width = 6.4,
  height = 4.6,
  dpi = 600,
  bg = "white"
)

ggsave(
  filename = file.path(out_dir, "SCI_Venn_Timepoint_DEGs_maSigPro_temporal_genes.tiff"),
  plot = p,
  width = 6.4,
  height = 4.6,
  dpi = 600,
  compression = "lzw",
  bg = "white"
)

############################################################
# 10) Finish
############################################################
cat("\n=================================================\n")
cat("SCI Venn finished.\n")
cat("Time-point DEGs:", n_deg, "\n")
cat("maSigPro temporal genes:", n_msp, "\n")
cat("Intersection:", n_int, "\n")
cat("Time-point DEG only:", n_deg_only, "\n")
cat("maSigPro temporal gene only:", n_msp_only, "\n")
cat("Output directory:\n")
cat(normalizePath(out_dir), "\n")
cat("=================================================\n")

















































############################################################
# 11) Additional output: Venn without set labels
#     Keep the same working directory and SCI-quality outputs
############################################################

p_no_label <- ggplot() +
  
  geom_circle(
    data = circle_left,
    aes(x0 = x0, y0 = y0, r = r),
    fill = COL_DEG,
    color = "black",
    alpha = 0.50,
    linewidth = 0.65
  ) +
  
  geom_circle(
    data = circle_right,
    aes(x0 = x0, y0 = y0, r = r),
    fill = COL_MSP,
    color = "black",
    alpha = 0.50,
    linewidth = 0.65
  ) +
  
  geom_text(
    data = count_df,
    aes(x = x, y = y, label = label),
    size = 6.4,
    fontface = "bold",
    color = "black"
  ) +
  
  coord_fixed(
    xlim = c(-2.05, 2.05),
    ylim = c(-1.35, 1.35),
    clip = "off"
  ) +
  
  theme_void(base_size = 13) +
  
  theme(
    legend.position = "none",
    plot.background = element_rect(fill = "white", color = NA),
    panel.background = element_rect(fill = "white", color = NA),
    plot.margin = margin(8, 8, 8, 8)
  )

ggsave(
  filename = file.path(out_dir, "SCI_Venn_Timepoint_DEGs_maSigPro_temporal_genes_no_title.pdf"),
  plot = p_no_label,
  width = 6.4,
  height = 4.6,
  bg = "white",
  device = cairo_pdf
)

ggsave(
  filename = file.path(out_dir, "SCI_Venn_Timepoint_DEGs_maSigPro_temporal_genes_no_title.png"),
  plot = p_no_label,
  width = 6.4,
  height = 4.6,
  dpi = 600,
  bg = "white"
)

ggsave(
  filename = file.path(out_dir, "SCI_Venn_Timepoint_DEGs_maSigPro_temporal_genes_no_title.tiff"),
  plot = p_no_label,
  width = 6.4,
  height = 4.6,
  dpi = 600,
  compression = "lzw",
  bg = "white"
)

cat("\nAdditional no-title Venn figure generated:\n")
cat(file.path(out_dir, "SCI_Venn_Timepoint_DEGs_maSigPro_temporal_genes_no_title.pdf"), "\n")